### ISSUE TITLE
(maybe) unexpected perf results

### ISSUE THREAD

**Issue by MoritzLoewenstein** [sass/embedded-host-node#109] opened 2022-01-29 00:31 UTC
Hey, i tested this as a drop-in replacement for the `sass` package,
compiling 48 files (~8k lines total) with no sass features besides nesting and variables.
These were the results (using `compile` & `compileAsync`):
sass-embedded sync 1.853s
sass-embedded async 460.744ms
sass sync 282.262ms
sass async 382.66ms
I have no issue with the current performance, but wanted to test the embedded version.
Are these expected performance results for my use-case, or could there be a problem?

**Comment by kevinramharak** [comment] 2022-01-29 01:07
Can you share how you are invoking it? A very quick test compiling bootstrap gives me these consistent results:
```
sass.compile took 1860.786ms
sass.compileAsync took 3400.456ms
embedded.compile took 479.108ms
embedded.compileAsync took 466.045ms
```

<details>
<summary>`test.js`</summary>

```js
// npm i sass sass-embedded bootstrap
const sass = require('sass');
const embedded = require('sass-embedded');

const content = "@import './node_modules/bootstrap/scss/bootstrap'";
/**
 * @type {import('sass').Options}
 */
const options = {
    // Need this for compile string
    loadPaths: ['.']
};

// by chaining we prevent async stuff and IO influencing other tasks
let current = Promise.resolve();
function measure(name, fn) {
    current = current.then(() => {
        const begin = performance.now();
        return Promise.resolve(fn()).then(() => {
            const end = performance.now();
            console.log(`${name} took ${(end - begin).toFixed(3)}ms`);
        });
    });
}

measure('sass.compile', () => sass.compileString(content, options));
measure('sass.compileAsync', () => sass.compileStringAsync(content, options));
measure('embedded.compile', () => embedded.compileString(content, options));
measure('embedded.compileAsync', () => embedded.compileStringAsync(content, options));
```
</details>

**Comment by MoritzLoewenstein** [comment] 2022-01-29 01:15
These were the 2 functions i used to compile an array of file paths, both returning an array with either css string or error.
I used `console.time` right before and after these function calls.
```js
function buildScssMultiple(localFilePaths) {
  return localFilePaths.map((filePath) => {
    try {
      const result = sass.compile(filePath, {
        sourceMap: false,
        style: "compressed",
      });
      return result.css;
    } catch (err) {
      return err;
    }
  });
}

async function buildScssMultipleAsync(localFilePaths) {
  const results = [];
  for (const filePath of localFilePaths) {
    try {
      const result = await sass.compileAsync(filePath, {
        sourceMap: false,
        style: "compressed",
      });
      results.push(result.css);
    } catch (err) {
      results.push(err);
    }
  }
  return results;
}
```

**Comment by kevinramharak** [comment] 2022-01-29 01:26
Using `async`/`await` this way still blocks a lot, try this:
```js
async function buildScssMultipleAsync(localFilePaths) {
  const results = [];
  await Promise.all(localFilePaths.map(async () => {
    try {
      const result = await sass.compileAsync(filePath, {
        sourceMap: false,
        style: "compressed",
      });
      results.push(result.css);
    } catch (err) {
      results.push(err);
    }
  }));
  return results;
}
```

Does that mean you are compiling 48 files seperately? or multiple projects with a total of 48 files?

**Comment by MoritzLoewenstein** [comment] 2022-01-29 01:39
The sass-embedded async  result improved to 211.055ms with this change.
I am giving the function an array of 48 paths in one project, but these files do not import each other. If I understand the question correctly it doesnt matter if these are from the same project or not in this case?

**Comment by kevinramharak** [comment] 2022-01-29 01:47
I'm not to familiar with the implementation details, but I assume there is some overhead in calling `compileAsync` each time. Not sure if that would be noticable.
Would love to take a look at a sample as I'm very invested in having `embedded-sass` being faster than the js version.

**Comment by MoritzLoewenstein** [comment] 2022-01-29 11:58
Hey, I created a small bench repo https://github.com/MoritzLoewenstein/sass-bench.git
If you have [hyperfine](https://github.com/sharkdp/hyperfine) installed you can just clone, `npm install` & `npm run bench`.
The benchmark is compiling the same scss file 50 times in one run, 10 runs per mode (3 runs warmup).
These are my results:
![image](https://user-images.githubusercontent.com/32882329/151660012-89c02d6f-bfd1-4bab-9825-7494a5011302.png)
The embedded async variant is always giving me the warning about statistical outliers, as you can see the runs vary between 0.4 and 1.4s. The embedded sync variant seems unusually slow as well.
My current (wild) guess is, that the embedded-host-protocol is the bottleneck, not the sass compiler if that makes sense?

**Comment by kevinramharak** [comment] 2022-01-29 14:10
Thank you for setting up that example.

That the embedded sync version is slower is expected, see the README.md:
> Unlike the sass package, the asynchronous API in sass-embedded will generally be faster than the synchronous API since the Sass compilation logic is happening in a different process.

---

I ran your setup with the following results:
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `node index.js --embedded --sync` | 5.321 ± 0.254 | 4.704 | 5.562 | 6.20 ± 0.32 |
| `node index.js --embedded` | 1.450 ± 0.155 | 1.342 | 1.872 | 1.69 ± 0.18 |
| `node index.js --sync` | 0.858 ± 0.016 | 0.825 | 0.882 | 1.00 |
| `node index.js` | 1.150 ± 0.141 | 1.071 | 1.508 | 1.34 ± 0.17 |

---

To make sure compiling the same file 50 times does not have an impact I compiled 50 seperate files with the same content:
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `node index.js --embedded --sync` | 5.007 ± 0.422 | 4.650 | 5.977 | 12.64 ± 1.18 |
| `node index.js --embedded` | 1.165 ± 0.055 | 1.122 | 1.305 | 2.94 ± 0.18 |
| `node index.js --sync` | 0.396 ± 0.016 | 0.381 | 0.427 | 1.00 |
| `node index.js` | 0.421 ± 0.013 | 0.404 | 0.446 | 1.06 ± 0.05 |

---

The problem with your setup is that the contents of `test.scss` is plain css with no language features of sass. If you look at the task the compiler has to do it will be roughly:
- read the file
- parse it
- compile it
- write the result

Since the example is to barebones this task will be done very quickly. So what your benchmark is actually measuring is the overhead that is introduced when invoking the `sass-embedded` version instead of the `sass` version. 

To draw a contrast here are the results of compiling bootstrap 50 times instead:
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `node index.js --embedded --sync` | 18.295 ± 0.276 | 17.793 | 18.785 | 2.43 ± 0.09 |
| `node index.js --embedded` | 7.521 ± 0.269 | 7.142 | 8.107 | 1.00 |
| `node index.js --sync` | 43.975 ± 20.322 | 28.890 | 88.061 | 5.85 ± 2.71 |
| `node index.js`| * | - | ~ 229 |
> * I terminated this one since its ETA was 38 minutes after running for a few minutes

When I compiled bootstrap just 10 times:
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `node index.js --embedded --sync` | 3.619 ± 0.161 | 3.495 | 3.921 | 2.47 ± 0.13 |
| `node index.js --embedded` | 1.464 ± 0.043 | 1.425 | 1.575 | 1.00 |
| `node index.js --sync` | 6.337 ± 0.419 | 5.828 | 6.968 | 4.33 ± 0.31 |


## Consusion

I think this is a pretty good example of how benchmarks can be deceiving. Understanding what part of the benchmark is the actual task you want to be measured is critical in getting results that you can rely on.

Your findings mostly measure the amount of overhead introduced by `embedded-sass` that does not happen in `sass`, but throws away all the reasons you would use `embedded-sass` over `sass`.

I think a good takeaway here is that if you are not using the sass language features or just use a few basic one, look into a more lightweight alternative like PostCSS with variables and nesting plugins.

**Comment by MoritzLoewenstein** [comment] 2022-01-29 15:08
Makes a lot of sense that a lot of small files are the worst case for the `sass-embedded` version, what is weird is that the variance using the `node index.js --embedded` command is very high. The other results are all fairly stable, but it would be interesting to know what causes this, especially because in your benchmark this doesnt happen.
This are the 10 times I measured, its really either ~1.4s or ~0.4s:
![image](https://user-images.githubusercontent.com/32882329/151665762-8a3e0f3e-7ec9-44fb-b07c-7eb9d7775294.png)
I dont think that it should behave this way, but there is probably a reasonable explanation?
The result stays the same even if I use 50 separate files with the same content.

**Comment by kevinramharak** [comment] 2022-01-29 16:39
I cannot reliably reproduce, maybe try and have hyperfine run more than 10 runs? It could be that your PC is doing other work during those tests. If I run it a few times there 1 run will give the warning:

```
Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
```

I would suggest running it a few times. I'm pretty sure its caused by external factors and not this library.

**Comment by MoritzLoewenstein** [comment] 2022-01-29 18:31
I am 99% sure it is not caused by external system load, just tested it multiple times with 100 runs.
In each run there was the large gap with not results between 0.5s & 1.3s.
I already tried hyperfine with `--prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches'` (this deletes all harddisk caches on linux before each run), but it did not change anything. I will try to profile this if I find time.

**Comment by nex3** [comment] 2022-02-01 00:36
I'm closing this out since, as people have mentioned, this performance difference comes down to the overhead of starting and stopping the embedded process over and over and will tend to disappear once you're compiling real Sass stylesheets instead.

It's worth noting that we could mitigate this overhead by adding the ability to re-use the embedded process for multiple compilations, but we'd need to come up with a good API for doing so.

**Closed by nex3** 2022-02-01 00:36 UTC
